#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#-------------------------------------------------------------------------------
# COLORS
#-------------------------------------------------------------------------------

BRD_CLR_NORMAL="#eaeaea"
BRD_CLR_ACTIVE="#eaeaea"
BRD_CLR_FOCUSED="#ffe566"
BRD_CLR_PRESEL="#ffe566"

bspc config normal_border_color    $BRD_CLR_NORMAL
bspc config active_border_color    $BRD_CLR_ACTIVE
bspc config focused_border_color   $BRD_CLR_FOCUSED
bspc config presel_feedback_color  $BRD_CLR_PRESEL

#-------------------------------------------------------------------------------
# TILED MODE
#-------------------------------------------------------------------------------

bspc config border_width       3
bspc config window_gap        16

#bspc config top_padding       24
#bspc config bottom_padding     0
#bspc config right_padding      0
#bspc config left_padding       0

#-------------------------------------------------------------------------------
# MONOCLE MODE
#-------------------------------------------------------------------------------

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

#bspc config top_monocle_padding       24
#bspc config bottom_monocle_padding     0
#bspc config right_monocle_padding      0
#bspc config left_monocle_padding       0

#-------------------------------------------------------------------------------
# BEHAVIOUR
#-------------------------------------------------------------------------------

bspc config automatic_scheme    longest_side
bspc config initial_polarity    second_child
bspc config focus_follows_pointer      false
bspc config presel_feedback             true

#-------------------------------------------------------------------------------
# RULES
#-------------------------------------------------------------------------------

# If refreshing bspwm, remove all previous rules to prevent doubling up
bspc rule -r "*"

bspc rule -a Zathura state=tiled

